
package com.cvele.intersections.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-11-01T11:16:14.373+01:00
 * Generated source version: 3.1.12
 * 
 */
public final class IntersectionsWS_IntersectionsWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.cvele.com/intersections/ws", "IntersectionsWSImpl");

    private IntersectionsWS_IntersectionsWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IntersectionsWSClientImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IntersectionsWSClientImpl ss = new IntersectionsWSClientImpl(wsdlURL, SERVICE_NAME);
        IntersectionsWS port = ss.getIntersectionsWSPort();  
        
        {
//        System.out.println("Invoking createIntersection...");
//        com.cvele.intersections.ws.model.Intersection _createIntersection_intersection = null;
//        int _createIntersection__return = port.createIntersection(_createIntersection_intersection);
//        System.out.println("createIntersection.result=" + _createIntersection__return);


        }
        {
        System.out.println("Invoking getIntersectionById...");
        int _getIntersectionById_id = 546;
        com.cvele.intersections.ws.model.Intersection _getIntersectionById__return = port.getIntersectionById(_getIntersectionById_id);
        System.out.println("getIntersectionById.result=" + _getIntersectionById__return.getId());


        }
        {
//        System.out.println("Invoking getAllIntersections...");
//        java.util.List<com.cvele.intersections.ws.model.Intersection> _getAllIntersections__return = port.getAllIntersections();
//        System.out.println("getAllIntersections.result=" + _getAllIntersections__return);


        }

        System.exit(0);
    }

}
