package com.cvele.intersections.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-10-31T21:06:45.209+01:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "IntersectionsWSImpl", 
                  //wsdlLocation = "file:intersections.wsdl",
                  targetNamespace = "http://www.cvele.com/intersections/ws") 
public class IntersectionsWSClientImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cvele.com/intersections/ws", "IntersectionsWSImpl");
    public final static QName IntersectionsWSPort = new QName("http://www.cvele.com/intersections/ws", "IntersectionsWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxf/ws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IntersectionsWSClientImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:intersections.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IntersectionsWSClientImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IntersectionsWSClientImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntersectionsWSClientImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IntersectionsWSClientImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IntersectionsWSClientImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IntersectionsWSClientImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IntersectionsWS
     */
    @WebEndpoint(name = "IntersectionsWSPort")
    public IntersectionsWS getIntersectionsWSPort() {
        return super.getPort(IntersectionsWSPort, IntersectionsWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntersectionsWS
     */
    @WebEndpoint(name = "IntersectionsWSPort")
    public IntersectionsWS getIntersectionsWSPort(WebServiceFeature... features) {
        return super.getPort(IntersectionsWSPort, IntersectionsWS.class, features);
    }

}
