package com.cvele.intersections.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-11-03T10:56:48.101+01:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.cvele.com/intersections/ws", name = "IntersectionsWS")
@XmlSeeAlso({com.cvele.intersections.ws.model.ObjectFactory.class, ObjectFactory.class})
public interface IntersectionsWS {

    @WebMethod
    @RequestWrapper(localName = "createIntersection", targetNamespace = "http://www.cvele.com/intersections/ws", className = "com.cvele.intersections.ws.CreateIntersection")
    @ResponseWrapper(localName = "createIntersectionResponse", targetNamespace = "http://www.cvele.com/intersections/ws", className = "com.cvele.intersections.ws.CreateIntersectionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int createIntersection(
        @WebParam(name = "intersection", targetNamespace = "")
        com.cvele.intersections.ws.model.Intersection intersection
    );

    @WebMethod
    @RequestWrapper(localName = "createMongoIntersection", targetNamespace = "http://www.cvele.com/intersections/ws", className = "com.cvele.intersections.ws.CreateMongoIntersection")
    @ResponseWrapper(localName = "createMongoIntersectionResponse", targetNamespace = "http://www.cvele.com/intersections/ws", className = "com.cvele.intersections.ws.CreateMongoIntersectionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String createMongoIntersection(
        @WebParam(name = "mongoIntersection", targetNamespace = "")
        com.cvele.intersections.ws.model.IntersectionMongo mongoIntersection
    );

    @WebMethod
    @RequestWrapper(localName = "getIntersectionById", targetNamespace = "http://www.cvele.com/intersections/ws", className = "com.cvele.intersections.ws.GetIntersectionById")
    @ResponseWrapper(localName = "getIntersectionByIdResponse", targetNamespace = "http://www.cvele.com/intersections/ws", className = "com.cvele.intersections.ws.GetIntersectionByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.cvele.intersections.ws.model.Intersection getIntersectionById(
        @WebParam(name = "id", targetNamespace = "")
        int id
    );

    @WebMethod
    @RequestWrapper(localName = "getAllIntersections", targetNamespace = "http://www.cvele.com/intersections/ws", className = "com.cvele.intersections.ws.GetAllIntersections")
    @ResponseWrapper(localName = "getAllIntersectionsResponse", targetNamespace = "http://www.cvele.com/intersections/ws", className = "com.cvele.intersections.ws.GetAllIntersectionsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cvele.intersections.ws.model.Intersection> getAllIntersections();
}
